// Code generated by protoc-gen-go. DO NOT EDIT.
// source: features.proto

package sample

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Containers to hold repeated fundamental values.
type BytesList struct {
	Value                [][]byte `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesList) Reset()         { *m = BytesList{} }
func (m *BytesList) String() string { return proto.CompactTextString(m) }
func (*BytesList) ProtoMessage()    {}
func (*BytesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{0}
}

func (m *BytesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesList.Unmarshal(m, b)
}
func (m *BytesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesList.Marshal(b, m, deterministic)
}
func (m *BytesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesList.Merge(m, src)
}
func (m *BytesList) XXX_Size() int {
	return xxx_messageInfo_BytesList.Size(m)
}
func (m *BytesList) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesList.DiscardUnknown(m)
}

var xxx_messageInfo_BytesList proto.InternalMessageInfo

func (m *BytesList) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type FloatList struct {
	Value                []float32 `protobuf:"fixed32,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FloatList) Reset()         { *m = FloatList{} }
func (m *FloatList) String() string { return proto.CompactTextString(m) }
func (*FloatList) ProtoMessage()    {}
func (*FloatList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{1}
}

func (m *FloatList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatList.Unmarshal(m, b)
}
func (m *FloatList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatList.Marshal(b, m, deterministic)
}
func (m *FloatList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatList.Merge(m, src)
}
func (m *FloatList) XXX_Size() int {
	return xxx_messageInfo_FloatList.Size(m)
}
func (m *FloatList) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatList.DiscardUnknown(m)
}

var xxx_messageInfo_FloatList proto.InternalMessageInfo

func (m *FloatList) GetValue() []float32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type Int64List struct {
	Value                []int64  `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64List) Reset()         { *m = Int64List{} }
func (m *Int64List) String() string { return proto.CompactTextString(m) }
func (*Int64List) ProtoMessage()    {}
func (*Int64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{2}
}

func (m *Int64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64List.Unmarshal(m, b)
}
func (m *Int64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64List.Marshal(b, m, deterministic)
}
func (m *Int64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64List.Merge(m, src)
}
func (m *Int64List) XXX_Size() int {
	return xxx_messageInfo_Int64List.Size(m)
}
func (m *Int64List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64List.DiscardUnknown(m)
}

var xxx_messageInfo_Int64List proto.InternalMessageInfo

func (m *Int64List) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

// Containers for non-sequential data.
type Feature struct {
	// Each feature can be exactly one kind.
	//
	// Types that are valid to be assigned to Kind:
	//	*Feature_BytesList
	//	*Feature_FloatList
	//	*Feature_Int64List
	Kind                 isFeature_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{3}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

type isFeature_Kind interface {
	isFeature_Kind()
}

type Feature_BytesList struct {
	BytesList *BytesList `protobuf:"bytes,1,opt,name=bytes_list,json=bytesList,proto3,oneof"`
}

type Feature_FloatList struct {
	FloatList *FloatList `protobuf:"bytes,2,opt,name=float_list,json=floatList,proto3,oneof"`
}

type Feature_Int64List struct {
	Int64List *Int64List `protobuf:"bytes,3,opt,name=int64_list,json=int64List,proto3,oneof"`
}

func (*Feature_BytesList) isFeature_Kind() {}

func (*Feature_FloatList) isFeature_Kind() {}

func (*Feature_Int64List) isFeature_Kind() {}

func (m *Feature) GetKind() isFeature_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Feature) GetBytesList() *BytesList {
	if x, ok := m.GetKind().(*Feature_BytesList); ok {
		return x.BytesList
	}
	return nil
}

func (m *Feature) GetFloatList() *FloatList {
	if x, ok := m.GetKind().(*Feature_FloatList); ok {
		return x.FloatList
	}
	return nil
}

func (m *Feature) GetInt64List() *Int64List {
	if x, ok := m.GetKind().(*Feature_Int64List); ok {
		return x.Int64List
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Feature) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Feature_BytesList)(nil),
		(*Feature_FloatList)(nil),
		(*Feature_Int64List)(nil),
	}
}

type Features struct {
	// Map from feature name to feature.
	Feature              map[string]*Feature `protobuf:"bytes,1,rep,name=feature,proto3" json:"feature,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Features) Reset()         { *m = Features{} }
func (m *Features) String() string { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()    {}
func (*Features) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{4}
}

func (m *Features) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features.Unmarshal(m, b)
}
func (m *Features) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features.Marshal(b, m, deterministic)
}
func (m *Features) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features.Merge(m, src)
}
func (m *Features) XXX_Size() int {
	return xxx_messageInfo_Features.Size(m)
}
func (m *Features) XXX_DiscardUnknown() {
	xxx_messageInfo_Features.DiscardUnknown(m)
}

var xxx_messageInfo_Features proto.InternalMessageInfo

func (m *Features) GetFeature() map[string]*Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

// Containers for sequential data.
//
// A FeatureList contains lists of Features.  These may hold zero or more
// Feature values.
//
// FeatureLists are organized into categories by name.  The FeatureLists message
// contains the mapping from name to FeatureList.
//
type FeatureList struct {
	Feature              []*Feature `protobuf:"bytes,1,rep,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FeatureList) Reset()         { *m = FeatureList{} }
func (m *FeatureList) String() string { return proto.CompactTextString(m) }
func (*FeatureList) ProtoMessage()    {}
func (*FeatureList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{5}
}

func (m *FeatureList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureList.Unmarshal(m, b)
}
func (m *FeatureList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureList.Marshal(b, m, deterministic)
}
func (m *FeatureList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureList.Merge(m, src)
}
func (m *FeatureList) XXX_Size() int {
	return xxx_messageInfo_FeatureList.Size(m)
}
func (m *FeatureList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureList.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureList proto.InternalMessageInfo

func (m *FeatureList) GetFeature() []*Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type FeatureLists struct {
	// Map from feature name to feature list.
	FeatureList          map[string]*FeatureList `protobuf:"bytes,1,rep,name=feature_list,json=featureList,proto3" json:"feature_list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FeatureLists) Reset()         { *m = FeatureLists{} }
func (m *FeatureLists) String() string { return proto.CompactTextString(m) }
func (*FeatureLists) ProtoMessage()    {}
func (*FeatureLists) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{6}
}

func (m *FeatureLists) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureLists.Unmarshal(m, b)
}
func (m *FeatureLists) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureLists.Marshal(b, m, deterministic)
}
func (m *FeatureLists) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureLists.Merge(m, src)
}
func (m *FeatureLists) XXX_Size() int {
	return xxx_messageInfo_FeatureLists.Size(m)
}
func (m *FeatureLists) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureLists.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureLists proto.InternalMessageInfo

func (m *FeatureLists) GetFeatureList() map[string]*FeatureList {
	if m != nil {
		return m.FeatureList
	}
	return nil
}

func init() {
	proto.RegisterType((*BytesList)(nil), "sample.BytesList")
	proto.RegisterType((*FloatList)(nil), "sample.FloatList")
	proto.RegisterType((*Int64List)(nil), "sample.Int64List")
	proto.RegisterType((*Feature)(nil), "sample.Feature")
	proto.RegisterType((*Features)(nil), "sample.Features")
	proto.RegisterMapType((map[string]*Feature)(nil), "sample.Features.FeatureEntry")
	proto.RegisterType((*FeatureList)(nil), "sample.FeatureList")
	proto.RegisterType((*FeatureLists)(nil), "sample.FeatureLists")
	proto.RegisterMapType((map[string]*FeatureList)(nil), "sample.FeatureLists.FeatureListEntry")
}

func init() { proto.RegisterFile("features.proto", fileDescriptor_2216f05915163cdf) }

var fileDescriptor_2216f05915163cdf = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x4d, 0xab, 0x9b, 0x3d, 0xad, 0x3a, 0xa3, 0xc8, 0x18, 0x08, 0xb3, 0x30, 0xd8, 0x40,
	0x7a, 0x51, 0x45, 0x87, 0x97, 0x05, 0xc7, 0x44, 0x2f, 0x46, 0x7d, 0x00, 0xe9, 0x30, 0x95, 0xb2,
	0xda, 0x8e, 0x26, 0x53, 0xf7, 0x16, 0xbe, 0x88, 0xef, 0xe7, 0xa5, 0xe4, 0x4f, 0x6b, 0xda, 0xed,
	0xae, 0xc9, 0xf9, 0xbe, 0x73, 0x7e, 0xdf, 0x69, 0xe0, 0x30, 0x26, 0x11, 0x5b, 0x15, 0x84, 0x7a,
	0xcb, 0x22, 0x67, 0x39, 0x6e, 0xd1, 0xe8, 0x7d, 0x99, 0x12, 0xf7, 0x02, 0xac, 0x60, 0xcd, 0x08,
	0x7d, 0x4a, 0x28, 0xc3, 0xa7, 0xb0, 0xf7, 0x11, 0xa5, 0x2b, 0xd2, 0x45, 0x7d, 0x73, 0xe8, 0x84,
	0xf2, 0xe0, 0x0e, 0xc0, 0x9a, 0xa4, 0x79, 0xc4, 0x84, 0xa4, 0xab, 0x4b, 0x8c, 0xc0, 0xe8, 0x20,
	0x4d, 0xf6, 0x90, 0xb1, 0x9b, 0xeb, 0x4d, 0x99, 0xa9, 0xcb, 0x7e, 0x10, 0xb4, 0x27, 0x92, 0x05,
	0xfb, 0x00, 0x73, 0x3e, 0xfc, 0x25, 0x4d, 0x28, 0xeb, 0xa2, 0x3e, 0x1a, 0xda, 0xfe, 0xb1, 0x27,
	0xc9, 0xbc, 0x0a, 0x6b, 0xba, 0x13, 0x5a, 0xf3, 0x8a, 0xd1, 0x07, 0x88, 0x39, 0x8d, 0xf4, 0x18,
	0x75, 0x4f, 0xc5, 0xc9, 0x3d, 0x71, 0x05, 0xed, 0x03, 0x24, 0x1c, 0x4d, 0x7a, 0xcc, 0xba, 0xa7,
	0x82, 0xe6, 0x9e, 0xa4, 0x3c, 0x04, 0x2d, 0xd8, 0x5d, 0x24, 0xd9, 0xab, 0xfb, 0x8d, 0x60, 0x5f,
	0xf1, 0x52, 0x7c, 0x0b, 0x6d, 0xb5, 0x47, 0x11, 0xcc, 0xf6, 0xcf, 0xab, 0xc9, 0xe5, 0x7a, 0xd5,
	0xc7, 0x7d, 0xc6, 0x8a, 0x75, 0x58, 0xaa, 0x7b, 0x8f, 0xe0, 0xe8, 0x05, 0xdc, 0x01, 0x73, 0x41,
	0xd6, 0x22, 0xb2, 0x15, 0xf2, 0x4f, 0x3c, 0x28, 0x37, 0x26, 0x23, 0x1d, 0x35, 0x1a, 0xab, 0xf5,
	0xdd, 0x19, 0x63, 0xe4, 0x8e, 0xc1, 0x56, 0xb7, 0x22, 0xdd, 0xa8, 0x09, 0xb5, 0xe1, 0x2d, 0xeb,
	0x7c, 0xf9, 0x8e, 0x66, 0xa5, 0x78, 0x0a, 0x8e, 0xaa, 0x95, 0xff, 0x80, 0x37, 0x18, 0x34, 0x1a,
	0x08, 0xad, 0x7e, 0x90, 0xe9, 0xec, 0xf8, 0xff, 0xa6, 0xf7, 0x0c, 0x9d, 0xa6, 0x60, 0x4b, 0xca,
	0x51, 0x3d, 0xe5, 0xc9, 0x96, 0x41, 0x5a, 0xd2, 0xe0, 0x12, 0xce, 0xf2, 0xe2, 0xcd, 0x63, 0x24,
	0xa3, 0x79, 0x11, 0xa7, 0xf9, 0xa7, 0x47, 0xbe, 0x84, 0x21, 0x38, 0x50, 0x8e, 0x19, 0x7f, 0xcd,
	0x74, 0x86, 0x7e, 0x11, 0x9a, 0xb7, 0xc4, 0xd3, 0xbe, 0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x14,
	0xd4, 0xf4, 0xaa, 0xec, 0x02, 0x00, 0x00,
}
